package engine;

import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

public class Database {
	//"Table" name
	private String name;
	//Each duple of the hashmap is a column of the DB
	private HashMap<String,List<String>> database;

	/**
	* Default empty Database constructor
	*/
	public Database() {
		super();
		this.database = new HashMap<>();
	}

	/**
	* Default Database constructor
	*/
	public Database(String name, HashMap<String,List<String>> database) {
		super();
		this.name = name;
		this.database = database;
	}

	/**
	* Returns value of name
	* @return
	*/
	public String getName() {
		return name;
	}

	/**
	* Sets new value of name
	* @param
	*/
	public void setName(String name) {
		this.name = name;
	}

	/**
	* Returns value of database
	* @return
	*/
	public HashMap<String,List<String>> getDatabase() {
		return database;
	}

	/**
	* Sets new value of database
	* @param
	*/
	public void setDatabase(HashMap<String,List<String>> database) {
		this.database = database;
	}

	/**
	* Whenever a new result is generated by the engine, write it in a new row
	* @param results represents the list of outputs of the webservice
	*/
	public void writeRow(HashMap<String,String> results){
		for (String col : results.keySet()) {
			if (this.database.get(col) == null) {
				List<String> values = new ArrayList<>();
				values.add(results.get(col));
				this.database.put(col, values);
			} else {
				this.database.get(col).add(results.get(col));
			}
		}
	}
}
